# Generated by Django 5.1.2 on 2024-11-12 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_video_remove_useranswer_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='thumbnail',
        ),
    ]
